### PR TITLE
bibliography

### PR DESCRIPTION
**Pull request by olivierverdier**

### CODE REVIEW

**Comment by adler-j** [comment]
> This branch has conflicts that must be resolved

I guess you have to rebase on master

**Comment by olivierverdier** [comment]
😭

**Comment by olivierverdier** [comment]
Perhaps you could recommend a good course on git, to be given soon? 😑

**Comment by adler-j** [comment]
Well I dunno about "good" but someone is holding a git course here at KTH next week :D

**Comment by olivierverdier** [comment]
😶

**Pull request closed without merging**
